# Cloudflare Pages project configuration.
name = "talpis-webinars"
pages_build_output_dir = "."
compatibility_date = "2026-06-22"

[[d1_databases]]
binding = "DB"
database_name = "talpis-webinars-leads"
database_id = "2ba8fb7d-4114-4409-b131-99f37bf5aaee"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "talpis-videos"

[env.production]
compatibility_date = "2026-06-22"

[[env.production.d1_databases]]
binding = "DB"
database_name = "talpis-webinars-leads"
database_id = "2ba8fb7d-4114-4409-b131-99f37bf5aaee"
migrations_dir = "migrations"

[[env.production.r2_buckets]]
binding = "VIDEOS"
bucket_name = "talpis-videos"
